name: porosenocheck
description: Discover the Porosenochek system today and change your perception of pet care services. Experience convenience, customization, and compassionâ€”all in one app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+20

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  

  #firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

  nb_utils: ^7.0.3
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  stream_transform: ^2.1.0
  uuid: ^4.4.0

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  permission_handler: ^11.3.1

  # State Management
  get: ^4.6.6  # Notification

  # Payment
  phonepe_payment_sdk: ^2.0.1
  flutter_stripe: ^11.0.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  pay: ^2.0.0
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/Katya-Solutions-LLC/flutter_paystack.git
      ref: 1.0.0

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery

  photo_view: ^0.15.0

  #intent
  android_intent_plus: ^5.0.2

  datepicker_dropdown: ^0.1.1+1
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  country_picker: ^2.0.26

  # MAP
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  #SHIMMER
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.2
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/images/walkthrough_images/
    - assets/images/dog_paw/
    - assets/images/pet_profile/
    - assets/images/sitter/
    - assets/images/notification/
    - assets/images/shop/
    - assets/images/choosepet/
    - assets/icons/profile_icons/
    - assets/icons/service_icons/
    - assets/icons/navigation/
    - assets/icons/upi_payment/
    - assets/images/brand/
    - assets/lottie/



